services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio-data:/data

  prefect:
    build:
      context: .
      dockerfile: docker/prefect.Dockerfile
    container_name: monda-prefect
    env_file:
      - .env
    ports:
      - "${PREFECT_PORT}:4200"
    volumes:
      - .:/app
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "prefect", "version"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  minio-data:
